# syntax=docker/dockerfile:1

##
## Build
##
FROM --platform=linux/amd64 golang:1.18.2-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./ ./

RUN go build -o ./build/indexer ./packages/indexer

##
## Deploy
##
FROM --platform=linux/amd64 gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /app /app

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["./app/build/indexer"]