# Server configurations
server:
  host: "localhost"
  port: 8080

# Database credentials
database:
  host: "127.0.0.1"
  user: "root"
  pass: "root"
  name: "example"
  port: 5432
  time_zone: "Asia/Shanghai"
  ssl_mode: "disable"

# JWT credentials
jwt:
  secret: "123!"
  pass_salt_length: 12
  expire_days: 30 #days
