# Server configurations
server:
  host: "localhost"
  port: 8080

# Database credentials
database:
  host: "127.0.0.1"
  username: "root"
  password: "root"
  name: "demo"
  port: 5432
  time_zone: "Asia/Shanghai"
  ssl_mode: "disable"

# Elastic search
elasticsearch:
  host: "http://localhost:9200"
  username: elastic
  password: elastic

# Rabbit MQ
rabbitmq:
  host: "localhost"
  port: 5672
  username: root
  password: root

# JWT credentials
jwt:
  secret: "jwt"
  pass_salt_length: 12
  expire_days: 30 #days
