# Server configurations
server:
  host: "0.0.0.0"
  port: 8080

# Redis
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0

# Database credentials
database:
  host: "postgres"
  username: "root"
  password: "root"
  name: "demo"
  port: 5432
  time_zone: "Asia/Shanghai"
  ssl_mode: "disable"

# Elastic search
elasticsearch:
  host: "http://elasticsearch:9200"
  username: elastic
  password: elastic

# Minio
minio:
  host: "minio"
  port: 10000
  accessKeyID: minio
  secretAccessKey: minio
  useSSL: false

# Rabbit MQ
rabbitmq:
  host: "rabbitmq"
  port: 5672
  username: root
  password: root

# JWT credentials
jwt:
  secret: "jwt"
  pass_salt_length: 12
  expire_days: 30 #days

# Trace
jaeger:
  service_name: "user-management"
  agent_endpoint: "95.111.248.127:6831"
  collector_endpoint: "95.111.248.127:14268/api/traces"