# Server configurations
server:
  host: "0.0.0.0"
  port: 8080

# Redis
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

# Database credentials
database:
  host: "localhost"
  username: "root"
  password: "root"
  name: "demo"
  port: 5432
  time_zone: "Asia/Shanghai"
  ssl_mode: "disable"

# Elastic search
elasticsearch:
  host: "http://localhost:9200"
  username: elastic
  password: elastic

# Minio
minio:
  host: "localhost"
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  public_url: "localhost:9000"

# Rabbit MQ
rabbitmq:
  host: "localhost"
  port: 5672
  username: root
  password: root

# JWT credentials
jwt:
  secret: "jwt"
  pass_salt_length: 12
  expire_days: 30 #days

# Trace
jaeger:
  service_name: "user-management"
  agent_endpoint: "127.0.0.1:6831"
  collector_endpoint: "127.0.0.1:14268/api/traces"

# Log
graylog:
  host: "localhost"
  port: 12201
  key: testkey

# swagger info
swagger:
  title: "gogo API"
  description: "This is a sample server"
  version: "1.0"
  host: "localhost:8080"
  schemes: ["http"]
  basepath: ""

# mail
mail:
  sender: "yourgmail@gmail.com"
  host: "smtp.gmail.com"
  port: 587
  username: "yourgmail@gmail.com"
  password: "yourpassword"
