name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: actions/checkout@v3
      - name: Build the API
        run: |
          docker build -t api:multistage -f Dockerfile.multistage.api .
          docker image tag api:multistage dotrung051093/gogo:api
          docker push dotrung051093/gogo:api
      - uses: actions/checkout@v3
      - name: Build the Indexer
        run: |
          docker build -t indexer:multistage -f Dockerfile.multistage.indexer .
          docker image tag indexer:multistage dotrung051093/gogo:indexer
          docker push dotrung051093/gogo:indexer
